<a href="https://colab.research.google.com/github/gulabpatel/Knowledge_Distillation/blob/main/1_knowledge_distillation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Knowledge Distillation
[Youtube](https://www.youtube.com/watch?v=0ZS2lLsZwBY)

[wikipedia](https://www.youtube.com/redirect?event=video_description&redir_token=QUFFLUhqazA4ZUt0QjF1Uk1INGItTkx4VENUNTFzTEJfZ3xBQ3Jtc0ttclppd1pEQ3VrUnpRQmszYjhIMmZ0VHJwelIwQVNJdlZYZm05UVdtd0FWNzZyamE3Q21JblpLeGdleDlZeEZLNE14ZTB6V2txd1FySTllRTdBZmhNVVFLOEJlR2JNbHh5R2huc0g0MTB6SDZfWFJXSQ&q=https%3A%2F%2Fen.wikipedia.org%2Fwiki%2FKnowledge_distillation)

[Arxiv](https://arxiv.org/pdf/1503.02531.pdf)



## Introduction to Knowledge Distillation

Knowledge Distillation is a procedure for model
compression, in which a small (student) model is trained to match a large pre-trained
(teacher) model. Knowledge is transferred from the teacher model to the student
by minimizing a loss function, aimed at matching softened teacher logits as well as
ground-truth labels.

The logits are softened by applying a "temperature" scaling function in the softmax,
effectively smoothing out the probability distribution and revealing
inter-class relationships learned by the teacher.

**Reference:**

- [Hinton et al. (2015)](https://arxiv.org/abs/1503.02531)

## Setup

In [1]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
import numpy as np
tf.random.set_seed(3)

## Construct `Distiller()` class

The custom `Distiller()` class, overrides the `Model` methods `train_step`, `test_step`,
and `compile()`. In order to use the distiller, we need:

- A trained teacher model
- A student model to train
- A student loss function on the difference between student predictions and ground-truth
- A distillation loss function, along with a `temperature`, on the difference between the
soft student predictions and the soft teacher labels
- An `alpha` factor to weight the student and distillation loss
- An optimizer for the student and (optional) metrics to evaluate performance

In the `train_step` method, we perform a forward pass of both the teacher and student,
calculate the loss with weighting of the `student_loss` and `distillation_loss` by `alpha` and
`1 - alpha`, respectively, and perform the backward pass. Note: only the student weights are updated,
and therefore we only calculate the gradients for the student weights.

In the `test_step` method, we evaluate the student model on the provided dataset.

In [2]:

class Distiller(keras.Model):
    def __init__(self, student, teacher):
        super(Distiller, self).__init__()
        self.teacher = teacher
        self.student = student

    def compile(self,optimizer,metrics,student_loss_fn,distillation_loss_fn,alpha=0.1,temperature=3,):
        """ Configure the distiller.
        Args:
            optimizer: Keras optimizer for the student weights
            metrics: Keras metrics for evaluation
            student_loss_fn: Loss function of difference between student
                predictions and ground-truth
            distillation_loss_fn: Loss function of difference between soft
                student predictions and soft teacher predictions
            alpha: weight to student_loss_fn and 1-alpha to distillation_loss_fn
            temperature: Temperature for softening probability distributions.
                Larger temperature gives softer distributions.
        """
        super(Distiller, self).compile(optimizer=optimizer, metrics=metrics)
        self.student_loss_fn = student_loss_fn
        self.distillation_loss_fn = distillation_loss_fn
        self.alpha = alpha
        self.temperature = temperature

    def train_step(self, data):
        # Unpack data
        x, y = data

        # Forward pass of teacher
        teacher_predictions = self.teacher(x, training=False)

        with tf.GradientTape() as tape:
            # Forward pass of student
            student_predictions = self.student(x, training=True)

            # Compute losses
            student_loss = self.student_loss_fn(y, student_predictions)
            distillation_loss = self.distillation_loss_fn(
                tf.nn.softmax(teacher_predictions / self.temperature, axis=1),
                tf.nn.softmax(student_predictions / self.temperature, axis=1),
            )
            loss = self.alpha * student_loss + (1 - self.alpha) * distillation_loss

        # Compute gradients
        trainable_vars = self.student.trainable_variables
        gradients = tape.gradient(loss, trainable_vars)

        # Update weights
        self.optimizer.apply_gradients(zip(gradients, trainable_vars))

        # Update the metrics configured in `compile()`.
        self.compiled_metrics.update_state(y, student_predictions)

        # Return a dict of performance
        results = {m.name: m.result() for m in self.metrics}
        results.update(
            {"student_loss": student_loss, "distillation_loss": distillation_loss}
        )
        return results

    def test_step(self, data):
        # Unpack the data
        x, y = data

        # Compute predictions
        y_prediction = self.student(x, training=False)

        # Calculate the loss
        student_loss = self.student_loss_fn(y, y_prediction)

        # Update the metrics.
        self.compiled_metrics.update_state(y, y_prediction)

        # Return a dict of performance
        results = {m.name: m.result() for m in self.metrics}
        results.update({"student_loss": student_loss})
        return results


## Create student and teacher models

Initialy, we create a teacher model and a smaller student model. Both models are
convolutional neural networks and created using `Sequential()`,
but could be any Keras model.

In [6]:
# Create the teacher
teacher = keras.Sequential(
    [
        keras.Input(shape=(28, 28, 1)),
        layers.Conv2D(256, (3, 3), strides=(2, 2), padding="same"),
        layers.LeakyReLU(alpha=0.2),
        layers.MaxPooling2D(pool_size=(2, 2), strides=(1, 1), padding="same"),
        layers.Conv2D(512, (3, 3), strides=(2, 2), padding="same"),
        layers.Flatten(),
        layers.Dense(10),
    ],
    name="teacher",
)

# Create the student
student = keras.Sequential(
    [
        keras.Input(shape=(28, 28, 1)),
        layers.Conv2D(8, (3, 3), strides=(2, 2), padding="same"),
        layers.LeakyReLU(alpha=0.2),
        layers.MaxPooling2D(pool_size=(2, 2), strides=(1, 1), padding="same"),
        layers.Conv2D(8, (3, 3), strides=(2, 2), padding="same"),
        layers.Flatten(),
        layers.Dense(10),
    ],
    name="student",
)

student_scratch = keras.Sequential(
    [
        keras.Input(shape=(28, 28, 1)),
        layers.Conv2D(8, (3, 3), strides=(2, 2), padding="same"),
        layers.LeakyReLU(alpha=0.2),
        layers.MaxPooling2D(pool_size=(2, 2), strides=(1, 1), padding="same"),
        layers.Conv2D(8, (3, 3), strides=(2, 2), padding="same"),
        layers.Flatten(),
        layers.Dense(10),
    ],
    name="student_scratch",
)

# Clone student for later comparison
#student_scratch = keras.models.clone_model(student)

In [7]:
teacher.summary()

Model: "teacher"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_6 (Conv2D)            (None, 14, 14, 256)       2560      
_________________________________________________________________
leaky_re_lu_3 (LeakyReLU)    (None, 14, 14, 256)       0         
_________________________________________________________________
max_pooling2d_3 (MaxPooling2 (None, 14, 14, 256)       0         
_________________________________________________________________
conv2d_7 (Conv2D)            (None, 7, 7, 512)         1180160   
_________________________________________________________________
flatten_3 (Flatten)          (None, 25088)             0         
_________________________________________________________________
dense_3 (Dense)              (None, 10)                250890    
Total params: 1,433,610
Trainable params: 1,433,610
Non-trainable params: 0
_________________________________________________

In [8]:
student.summary()

Model: "student"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_8 (Conv2D)            (None, 14, 14, 8)         80        
_________________________________________________________________
leaky_re_lu_4 (LeakyReLU)    (None, 14, 14, 8)         0         
_________________________________________________________________
max_pooling2d_4 (MaxPooling2 (None, 14, 14, 8)         0         
_________________________________________________________________
conv2d_9 (Conv2D)            (None, 7, 7, 8)           584       
_________________________________________________________________
flatten_4 (Flatten)          (None, 392)               0         
_________________________________________________________________
dense_4 (Dense)              (None, 10)                3930      
Total params: 4,594
Trainable params: 4,594
Non-trainable params: 0
_________________________________________________________

In [9]:
student_scratch.summary()

Model: "student_scratch"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_10 (Conv2D)           (None, 14, 14, 8)         80        
_________________________________________________________________
leaky_re_lu_5 (LeakyReLU)    (None, 14, 14, 8)         0         
_________________________________________________________________
max_pooling2d_5 (MaxPooling2 (None, 14, 14, 8)         0         
_________________________________________________________________
conv2d_11 (Conv2D)           (None, 7, 7, 8)           584       
_________________________________________________________________
flatten_5 (Flatten)          (None, 392)               0         
_________________________________________________________________
dense_5 (Dense)              (None, 10)                3930      
Total params: 4,594
Trainable params: 4,594
Non-trainable params: 0
_________________________________________________

## Prepare the dataset

The dataset used for training the teacher and distilling the teacher is
[MNIST](https://keras.io/api/datasets/mnist/), and the procedure would be equivalent for any other
dataset, e.g. [CIFAR-10](https://keras.io/api/datasets/cifar10/), with a suitable choice
of models. Both the student and teacher are trained on the training set and evaluated on
the test set.

In [10]:
# Prepare the train and test dataset.
batch_size = 128
(x_train, y_train), (x_test, y_test) = keras.datasets.mnist.load_data()

# Normalize data
x_train = x_train.astype("float32") / 255.0
x_train = np.reshape(x_train, (-1, 28, 28, 1))

x_test = x_test.astype("float32") / 255.0
x_test = np.reshape(x_test, (-1, 28, 28, 1))


11501568/11490434 [==============================] - 0s 0us/step


## Train the teacher

In knowledge distillation we assume that the teacher is trained and fixed. Thus, we start
by training the teacher model on the training set in the usual way.

In [11]:
# Train teacher as usual
teacher.compile(
    optimizer=keras.optimizers.Adam(),
    loss=keras.losses.SparseCategoricalCrossentropy(from_logits=True),
    metrics=[keras.metrics.SparseCategoricalAccuracy()],
)

# Train and evaluate teacher on data.
teacher.fit(x_train, y_train, epochs=5)
print("---Testing Accuracy---")
teacher.evaluate(x_test, y_test)

Epoch 1/5
1875/1875 [==============================] - 490s 261ms/step - loss: 0.1414 - sparse_categorical_accuracy: 0.9570
Epoch 2/5
1875/1875 [==============================] - 489s 261ms/step - loss: 0.0924 - sparse_categorical_accuracy: 0.9725
Epoch 3/5
1875/1875 [==============================] - 491s 262ms/step - loss: 0.0818 - sparse_categorical_accuracy: 0.9761
Epoch 4/5
1875/1875 [==============================] - 491s 262ms/step - loss: 0.0763 - sparse_categorical_accuracy: 0.9789
Epoch 5/5
1875/1875 [==============================] - 487s 259ms/step - loss: 0.0681 - sparse_categorical_accuracy: 0.9808
---Testing Accuracy---
313/313 [==============================] - 20s 64ms/step - loss: 0.1212 - sparse_categorical_accuracy: 0.9732


[0.12118469178676605, 0.9732000231742859]

## Distill teacher to student

We have already trained the teacher model, and we only need to initialize a
`Distiller(student, teacher)` instance, `compile()` it with the desired losses,
hyperparameters and optimizer, and distill the teacher to the student.

In [12]:
# Initialize and compile distiller
distiller = Distiller(student=student, teacher=teacher)
distiller.compile(
    optimizer=keras.optimizers.Adam(),
    metrics=[keras.metrics.SparseCategoricalAccuracy()],
    student_loss_fn=keras.losses.SparseCategoricalCrossentropy(from_logits=True),
    distillation_loss_fn=keras.losses.KLDivergence(),
    alpha=0.1,
    temperature=40,
)

# Distill teacher to student
distiller.fit(x_train, y_train, epochs=5)
print("---Testing Accuracy---")
# Evaluate student on test dataset
distiller.evaluate(x_test, y_test)

Epoch 1/5
1875/1875 [==============================] - 128s 68ms/step - sparse_categorical_accuracy: 0.8721 - student_loss: 0.4329 - distillation_loss: 0.0208
Epoch 2/5
1875/1875 [==============================] - 127s 68ms/step - sparse_categorical_accuracy: 0.9356 - student_loss: 0.2257 - distillation_loss: 0.0139
Epoch 3/5
1875/1875 [==============================] - 128s 68ms/step - sparse_categorical_accuracy: 0.9582 - student_loss: 0.1551 - distillation_loss: 0.0083
Epoch 4/5
1875/1875 [==============================] - 128s 68ms/step - sparse_categorical_accuracy: 0.9645 - student_loss: 0.1274 - distillation_loss: 0.0064
Epoch 5/5
1875/1875 [==============================] - 128s 68ms/step - sparse_categorical_accuracy: 0.9693 - student_loss: 0.1112 - distillation_loss: 0.0056
---Testing Accuracy---
313/313 [==============================] - 1s 2ms/step - sparse_categorical_accuracy: 0.9708 - student_loss: 0.1056


[0.97079998254776, 0.0029277901630848646]

## Train student from scratch for comparison

We can also train an equivalent student model from scratch without the teacher, in order
to evaluate the performance gain obtained by knowledge distillation.

In [13]:
# Train student as done usually
student_scratch.compile(
    optimizer=keras.optimizers.Adam(),
    loss=keras.losses.SparseCategoricalCrossentropy(from_logits=True),
    metrics=[keras.metrics.SparseCategoricalAccuracy()],
)

# Train and evaluate student trained from scratch.
student_scratch.fit(x_train, y_train, epochs=5)
student_scratch.evaluate(x_test, y_test)

Epoch 1/5
1875/1875 [==============================] - 10s 5ms/step - loss: 0.3348 - sparse_categorical_accuracy: 0.9000
Epoch 2/5
1875/1875 [==============================] - 10s 5ms/step - loss: 0.1428 - sparse_categorical_accuracy: 0.9573
Epoch 3/5
1875/1875 [==============================] - 10s 5ms/step - loss: 0.1109 - sparse_categorical_accuracy: 0.9671
Epoch 4/5
1875/1875 [==============================] - 11s 6ms/step - loss: 0.0936 - sparse_categorical_accuracy: 0.9721
Epoch 5/5
313/313 [==============================] - 1s 2ms/step - loss: 0.0758 - sparse_categorical_accuracy: 0.9766


[0.07584298402070999, 0.9765999913215637]

If the teacher is trained for 5 full epochs and the student is distilled on this teacher
for 3 full epochs, you should in this example experience a performance boost compared to
training the same student model from scratch, and even compared to the teacher itself.
You should expect the teacher to have accuracy around 97.6%, the student trained from
scratch should be around 97.6%, and the distilled student should be around 98.1%. Remove
or try out different seeds to use different weight initializations.